services:
  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    ports: ["29092:29092"]
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  kafka-init:
    image: apache/kafka:3.8.0
    depends_on: [kafka]
    restart: "no"
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "sleep 10 && /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092
      --create --if-not-exists --topic checkout.events --partitions 3 --replication-factor 1"

  localstack:
    image: localstack/localstack:3.0
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DEFAULT_REGION: us-east-1

  localstack-init:
    image: curlimages/curl:8.9.1
    depends_on: [localstack]
    restart: "no"
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "sleep 8 && curl -X PUT http://localstack:4566/warehouse"

  iceberg-rest:
    image: tabulario/iceberg-rest:1.6.0
    container_name: iceberg-rest
    depends_on: [localstack-init]
    ports:
      - "8181:8181"
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      CATALOG_WAREHOUSE: s3://warehouse/
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      CATALOG_S3_ENDPOINT: http://localstack:4566
      CATALOG_S3_PATH__STYLE__ACCESS: "true"

  jobmanager:
    build: ./infra/flink
    container_name: jobmanager
    command: jobmanager
    ports:
      - "8081:8081"
    volumes:
      - ./flink/sql:/opt/sql
    environment: &flinkenv
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
        state.backend: hashmap
        execution.checkpointing.interval: 10s

  taskmanager:
    build: ./infra/flink
    container_name: taskmanager
    command: taskmanager
    depends_on: [jobmanager]
    environment: *flinkenv

volumes:
  iceberg-warehouse: